Add Gemfile to specify correct dependencies
The new Gemfile locks the activemodel version.

The ruby-trello gem is not specifying the activemodel version.
The currently most up to date version contains changes that breaks the
 ruby-trello 1.6.0 version when calling card.save.

Usage:
install$ bundle install
install$ bundle exec list2card -c ../etc/config.toml

```
E, [2019-12-15T18:59:40.803887 #123] ERROR -- : undefined method `changed?' for "5df66fd53b9db80b4404f2cf":String (NoMethodError)
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/attribute_mutation_tracker.rb:76:in `attribute_changed?'
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/attribute_mutation_tracker.rb:46:in `changed?'
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/attribute_mutation_tracker.rb:36:in `change_to_attribute'
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/attribute_mutation_tracker.rb:29:in `block in changes'
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/attribute_mutation_tracker.rb:28:in `each'
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/attribute_mutation_tracker.rb:28:in `each_with_object'
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/attribute_mutation_tracker.rb:28:in `changes'
/usr/local/bundle/gems/activemodel-6.0.2/lib/active_model/dirty.rb:218:in `changes'
/usr/local/bundle/gems/ruby-trello-1.6.0/lib/trello/card.rb:275:in `update!'
/usr/local/bundle/gems/ruby-trello-1.6.0/lib/trello/card.rb:248:in `save'
/usr/local/bundle/gems/trello-list2card-0.1.1/lib/trello/list2card.rb:164:in `block in do_run'
/usr/local/bundle/gems/ruby-trello-1.6.0/lib/trello/association_proxy.rb:23:in `each'
/usr/local/bundle/gems/ruby-trello-1.6.0/lib/trello/association_proxy.rb:23:in `method_missing'
/usr/local/bundle/gems/trello-list2card-0.1.1/lib/trello/list2card.rb:158:in `do_run'
/usr/local/bundle/gems/trello-list2card-0.1.1/bin/list2card:56:in `<top (required)>'
/usr/local/bundle/bin/list2card:23:in `load'
/usr/local/bundle/bin/list2card:23:in `<main>'
E, [2019-12-15T18:59:40.809341 #123] ERROR -- : Failed to archive '5df66fd53b9db80b4404f2cf'
I, [2019-12-15T18:59:40.809426 #123]  INFO -- : Done
```